services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./adn-alert-frontend/src/config/mosquitto:/mosquitto/config

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: adn_alert_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contraseña
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend1:
    build:
      context: ./adn-alert-backend
    container_name: backend1
    ports:
      - "8001:8000"
    environment:
      - DB_NAME=adn_alert_db
      - DB_USER=postgres
      - DB_PASSWORD=contraseña
      - DB_HOST=postgres
      - DB_PORT=5432
      - BACKEND_NAME=🔥 BACKEND 1  # 👈 Aquí

  backend2:
    build:
      context: ./adn-alert-backend
    container_name: backend2
    ports:
      - "8002:8000"
    environment:
      - DB_NAME=adn_alert_db
      - DB_USER=postgres
      - DB_PASSWORD=contraseña
      - DB_HOST=postgres
      - DB_PORT=5432
      - BACKEND_NAME=🧊 BACKEND 2  # 👈 Y aquí


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./adn-alert-frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2

  frontend:
    build:
      context: ./adn-alert-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    environment:
      - REACT_APP_WEBSOCKET_URL=ws://localhost:8000/ws
    stdin_open: true
    tty: true

volumes:
  postgres_data:
