server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Logs consolidados del sistema ADN Alert
  - job_name: adn-alert-system
    static_configs:
      - targets:
          - localhost
        labels:
          job: adn-alert-logs
          service: adn-alert-system
          __path__: /shared/logs/consolidated/*.log
    pipeline_stages:
      - json:
          expressions:
            service_name: service_name
            timestamp: timestamp
            log_level: log_level
            message: message
      - labels:
          service_name:
          log_level:
      - timestamp:
          source: timestamp
          format: RFC3339

  # Logs específicos de backend desde Docker
  - job_name: backend-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(backend[12])'
        target_label: container_name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(backend[12])'
        target_label: job
        replacement: backend
      - source_labels: ['__meta_docker_container_name']
        regex: '/(backend[12])'
        target_label: service
        replacement: adn-alert-backend

  # Logs del sistema
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          service: system
          __path__: /var/log/*.log
